import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { useEffect, useState } from "react";
import axios from "axios";


export default function Home() {
  const [pokemonList, setPokemonList] = useState([]); 
  //{name: "hoge", url: "fuga"}
  //url→sprites.front_default png
  const POKEMON_LIST_URL = "https://pokeapi.co/api/v2/pokemon?limit=100000&offset=0";

  useEffect(()=>{
    axios.get(POKEMON_LIST_URL)
    .then((res)=>{
      setPokemonList(res.data.results);
    }).catch((err)=>{
      console.log(err);
    });
  }, []);
  const getIdFromUrl = (url_str)=>{
    const id = url_str.slice(34,-1);
    return id;
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Practice Poké api</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.icon" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />
    
      </Head>
      <header>
        <p>Pokémon Search</p>
      </header>
      <main className={styles.main}>
        <h1>Did you find the Pokémon you wanted to know about?</h1>
        <table>
          <thead>
            <tr>
              <td>Index</td>
              <td>Name</td>
              <td>Detail</td>
            </tr>
          </thead>
          <tbody>
            {pokemonList.map((pokemon, index)=>{
              const pokemonId = getIdFromUrl(pokemon.url);
              return(
                <tr key={pokemonId}>
                  
                  <td>{index+1}</td>
                  <td>{pokemon.name}</td>
                  <td>
                  <Link
                    href={`/pokemon/${pokemonId}`}
                  >
                    <a className={styles.icon}>🔍</a>
                  </Link>
                  </td>
                </tr>
              );
            })}
          </tbody>
          
        </table>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>

        <a
          href='https://github.com/Muna-akki'
          className={styles.writer}
        >
          made by Muna-akki
        </a>
      </footer>
    </div>
  )
}
